name: test
on: [push]
env:
  POETRY_VERSION: 1.8.2
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}-0

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root --all-extras
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry install --no-interaction --all-extras

      # And finally run tests. I'm using pytest and all my pytest config is in my `pyproject.toml`
      # so this line is super-simple. But it could be as complex as you need.
      - run: poetry run pytest
      - run: poetry run tf-apply # "integration" type test

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements for documentation generation
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install docutils pydoctor

      - name: Generate API documentation with pydoctor
        run: |

          # Run pydoctor build
          pydoctor \
              --project-name="step-in-line" \
              --project-url=https://github.com/$GITHUB_REPOSITORY \
              --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
              --make-html \
              --html-output=./apidocs \
              --project-base-dir="$(pwd)" \
              --docformat=restructuredtext \
              --intersphinx=https://docs.python.org/3/objects.inv \
              ./step_in_line